### PR TITLE
Simplify Redux app using redux-starter-kit

### PR DESCRIPTION
**Pull request by markerikson**
I've rewritten the Redux app in this example [using our new `redux-starter-kit` package](https://github.com/reduxjs/redux-starter-kit).  

In the process:

- I removed `redux-saga` and `Immutable.js` entirely
- The fetch logic, which was previously handled by a saga, is now handled in a thunk that uses async/await.
- The Redux logic is now all written in a single file, `src/features/featureSets.js`, which is only 55 lines long.  (For comparison, the MobX `ValueSetStore.js` file is 81 lines long, although that could also be shortened.) All the previous separate Redux-related files and folders have been removed, as they're no longer necessary.
- There's no hand-written action creators or action type constants, and no spreads in any of the reducers
- The component logic was simplified as well.
- The separate dependency on `redux-devtools-extension` was removed, as that is handled internally by the starter kit's `configureStore()` function
- I moved the store setup to a separate `store.js` file, but it could easily have stayed in `App.js`, and it's only about 5 lines anyway.

I probably would have written things a bit more verbosely in a real app, but this helps prove that Redux itself doesn't _have_ to be verbose, and that you can simplify Redux-based code considerably using `redux-starter-kit`.

### CODE REVIEW

**Comment by xinsight** [comment]
Thanks for your contribution!

There's a lot to digest here - I'm thinking I might add this to a separate redux project directory so that people can compare sagas to thunks, and see what redux-starter-kit offers.

I noticed that there are 3 identical network requests with your version - but there should be only one. Could that be fixed by just checking `isLoading` in your fetchValueSet request?

**Comment by markerikson** [comment]
Aha.  That's the one aspect of the original saga logic I didn't notice the first time around:

https://github.com/xinsight/mobx-redux-showdown/blob/3e6da448823549e36c4947b2466fb73be03b5f19/redux-app/src/redux/sagas/sagas.js#L37-L48

Yup, easily fixed.  Pushing that change now.

**Comment by markerikson** [comment]
Really, the key points here are:

- Sagas were never necessary in the first place.  If you just want to do basic AJAX requests, thunks are all you need, and `async/await` makes that logic nicer to look at.
- `redux-starter-kit` removes most of the need to write action creators and action types by hand, and lets you write immutable reducer logic as simple "normal" mutative logic (without object spreads and such). It also simplifies a lot of the store setup process as well
- While there's perfectly good reasons to split your different types of Redux-related functions into different files, Redux itself [has never required that you do that](https://redux.js.org/faq/codestructure#what-should-my-file-structure-look-like-how-should-i-group-my-action-creators-and-reducers-in-my-project-where-should-my-selectors-go).

**Comment by xinsight** [comment]
Nice. One other issue - if I change the url to return a 404 - there should be an error when trying to parse the JSON structure. (This is actually a bug in the other implementations, but they do show an error.) Your version just shows a '-' and i'm not sure why. It looks like something is adding undefined as a key?

screen shot 2018-11-25 at 20 05 00

**Comment by markerikson** [comment]
Looks like I missed a line when I was converting the dispatching over to use the generated action creators.  Currently, the starter kit expects you to pass in the entire value of the `payload` field as one argument.  I was still passing the ID and error message as two arguments, so the action's contents were wrong.  Pushed a fix.

**Comment by xinsight** [comment]
Lots of good stuff to digest here, thanks again. I've made this it's own project in PR #2 (mainly so people can compare sagas/thunks and hand-written action creators vs automatic), so I'll close this PR.

**Pull request closed without merging**
